### ISSUE TITLE
requests

### ISSUE THREAD

**Issue by HamedAlmanthari** [Higgins4k/BetterTerminal#1]
hello. really nice mod, i think i'll use it from now on instead of the others. i have some requests that would be nice if you could add them:
1. itp for inverse teleporter.
2. change credits position to prevent overlapping with other texts. like move it to top right corner, bottom right corner, or something like that from the config.
3. shortcuts for some commands. like go for launch, or light for lights.
4. extras, not really necessary: 1. clock. 2. type as soon as you enter terminal

**Comment by Higgins4k** [comment]
I'll look into adding these over the weekend, thanks for the suggestions!

**Comment by HamedAlmanthari** [comment]
thank you! also another fix for text overlapping instead of changing credit position is to make it so that when you scroll down, any text that goes under the top part of the terminal becomes invisible. idk if you can do that honestly. if that is difficult just leave it. it's like the top part of the terminal is the navigation bar and anything that goes under the navigation bar is not visible if that makes sense.

**Comment by HamedAlmanthari** [comment]
restart would be nice too

**Comment by HamedAlmanthari** [comment]
idk if what i said earlier about texts overlapping is caused by a mod or it's in the base game. if it's caused by a mod then sorry lmao. that's embarassing.

**Comment by Higgins4k** [comment]
itp and inverse were added as commands
Text overlapping when scrolling I can't fix but it shouldn't happen when running commands, If it does outside of commands from my mod its another mod causing it. Should have a fix for vanilla and my mods commands. Let me know if you find a issue and Ill look into it
Made typing when entering terminal 80% faster
Restart has been added for Host only

Aliases added:
scan (inside/ship) - ScanInside & Items command
light - Lights command
teleport - Tp command
doors - Door Command
Land/Go - Launch Command
Inverse - Itp Command


Still to do:
Add a clock (Config if enabled)
Credit Move around screen corners (Config)
Add History
Add Autocompleting


If I missed anything you brought up or you have anymore suggestions/find a issue openup another Issue on Github. This will be live on Thunderstore soon under 1.0.7

**Comment by HamedAlmanthari** [comment]
damn that's really nice. ty!

**Comment by HamedAlmanthari** [comment]
i think you missed no. 2 but it's alright don't worry about it. it's not really that important.

**Comment by Higgins4k** [comment]
> i think you missed no. 2 but it's alright don't worry about it. it's not really that important.

I'll add moving Credit around the screen to the to-do list, That's a good way around it overlapping. Didn't think of that and didn't see it

**Comment by HamedAlmanthari** [comment]
alright. ty!
