### ISSUE TITLE
Love the mod, would like configs

### ISSUE THREAD

**Issue by Slendykins** [Higgins4k/BetterTerminal#2]
Hey i've played around with the mod for a little bit and I really enjoy it over the other API,

I was wondering if you could implement a config for what commands could be disabled/enabled?

Personally I wouldn't like the restart command there even if it's for host only, or at least without confirmation first.

**Comment by Higgins4k** [comment]
Thanks to @Moose1301 this will be coming in the next update which should be posted tonight
